export const menu = [
    {
        id:1,
        title:'vennder',
        path:'vender',
        children:[
            'vender','abc','wewe',
        ],
        id:2,
        title:'vennder',
        path:'vender',
        children:[
            'vender','abc','wewe',
        ],
        id:3,
        title:'vennder',
        path:'vender',
        children:[
            'vender','abc','wewe',
        ],
    }
]